### ISSUE TITLE
Hide error traceback

### ISSUE THREAD

**Issue by tm-a-t** [tm-a-t/TGPy#39]
TGPy messages with errors look quite like random spam, and full error tracebacks are rarely useful.

I am proposing to show only the last line of the error and save the full error to a variable and/or logs.

### Example

Current behavior:

```
msg.something

TGPy> Error occurred

Traceback (most recent call last):
  File "/home/tmat/.local/pipx/venvs/tgpy/lib/python3.11/site-packages/tgpy/_core/meval.py", line 175, in _meval
    new_locs, ret = await getattr(py_module, 'tmp')(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tgpy://message/-1001611149679/38326", line 1, in tmp
    msg.something
AttributeError: 'Message' object has no attribute 'something'
```

Suggested behavior:
```
msg.something

TGPy> AttributeError: 'Message' object has no attribute 'something'
```

**Comment by vanutp** [comment]
Implemented in https://github.com/tm-a-t/TGPy/commit/739fbbcdc2f96ed54a10620f87049b0107c14cc6
