### ISSUE TITLE
Error when using cancel in topics

### ISSUE THREAD

**Issue by vanutp** [tm-a-t/TGPy#40]
cancel command throws errors when used in topic-enabled chats
```

Traceback (most recent call last):
  File "/app/tgpy/_handlers/__init__.py", line 24, in result
    await func(message)
  File "/app/tgpy/_handlers/__init__.py", line 73, in on_new_message
    await handle_message(event.message)
  File "/app/tgpy/_handlers/__init__.py", line 51, in handle_message
    if not (message := await exec_hooks.apply(original_message, is_edit=False)):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tgpy/api/transformers.py", line 122, in apply
    hook_ret = await try_await(hook, message, is_edit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tgpy/api/utils.py", line 88, in try_await
    res = await res
          ^^^^^^^^^
  File "tgpy://builtin_module/prevent_eval", line 87, in exec_hook
    await handle_cancel(message, permanent=is_cancel)
  File "tgpy://builtin_module/prevent_eval", line 56, in handle_cancel
    await cancel_message(target, permanent)
  File "tgpy://builtin_module/prevent_eval", line 30, in cancel_message
    message = await message.edit(parsed.code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/tl/custom/message.py", line 832, in edit
    return await self._client.edit_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/messages.py", line 1210, in edit_message
    msg = self._get_response_message(request, await self(request), entity)
                                              ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.MessageNotModifiedError: Content of the message was not modified (caused by EditMessageRequest)
```

```
Traceback (most recent call last):
  File "/app/tgpy/_handlers/__init__.py", line 24, in result
    await func(message)
  File "/app/tgpy/_handlers/__init__.py", line 73, in on_new_message
    await handle_message(event.message)
  File "/app/tgpy/_handlers/__init__.py", line 51, in handle_message
    if not (message := await exec_hooks.apply(original_message, is_edit=False)):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tgpy/api/transformers.py", line 122, in apply
    hook_ret = await try_await(hook, message, is_edit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tgpy/api/utils.py", line 88, in try_await
    res = await res
          ^^^^^^^^^
  File "tgpy://builtin_module/prevent_eval", line 87, in exec_hook
    await handle_cancel(message, permanent=is_cancel)
  File "tgpy://builtin_module/prevent_eval", line 56, in handle_cancel
    await cancel_message(target, permanent)
  File "tgpy://builtin_module/prevent_eval", line 30, in cancel_message
    message = await message.edit(parsed.code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/tl/custom/message.py", line 832, in edit
    return await self._client.edit_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/messages.py", line 1210, in edit_message
    msg = self._get_response_message(request, await self(request), entity)
                                              ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.MessageIdInvalidError: The specified message ID is invalid or you can't do that operation on such message (caused by EditMessageRequest)
```

also idk if those tracebacks are both for this issue, maybe not

**Comment by vanutp** [comment]
Fixed in 1d3ba1ab583f7408f9f2854d22bfcf7fc7e96ae7
